SeekerPlus\AdsmanagerBundle\Entity\AdsInbox:
    type: entity
    table: seeker_ad_inbox
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        idUserOrigin:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
            column: id_user_origin
        idUserDestination:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
            column: id_user_destination
        subjectInbox:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: ''
            column: subject_inbox
        messajeInbox:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: ''
            column: messaje_inbox
        state:
            type: string
            nullable: true
            length: 45
            fixed: false
            comment: ''
        dateCreated:
            type: date
            nullable: true
            comment: ''
            column: date_created
    lifecycleCallbacks: {  }
